### ISSUE TITLE
Update 1.15.0 and above has conflict with Modern Events Calendar plugin for WordPress

### ISSUE THREAD

**Issue by dchacon1** [bookingactivities/booking-activities#163]
I manage an internal site for my company that utilizes many different plugins including the Booking Activities plugin. I noticed that after updating to 1.15.0 or later the Booking Activities calendar no longer appears. Instead, the following JavaScript error appears:

`Uncaught TypeError: flushSync is not a function
    at Calendar._this.handleRenderRequest [as drainedOption] (main.js?ver=5.11.3:9842:21)
    at DelayedRunner.drained (main.js?ver=5.11.3:7004:22)
    at DelayedRunner.tryDrain (main.js?ver=5.11.3:6986:26)
    at DelayedRunner.request (main.js?ver=5.11.3:6947:26)
    at Calendar.render (main.js?ver=5.11.3:9882:31)
    at bookacti_set_calendar_up (booking-method-calendar.min.js?ver=1.15.1:1:10557)
    at HTMLDivElement.<anonymous> (booking-method-calendar.min.js?ver=1.15.1:1:184)
    at HTMLBodyElement.dispatch (jquery.min.js?ver=3.6.0:2:43064)
    at v.handle (jquery.min.js?ver=3.6.0:2:41048)
    at Object.trigger (jquery.min.js?ver=3.6.0:2:71515)`

Oddly enough, the plugin works fine if I deactivate my other plugin called **Modern Events Calendar**, however, both plugins worked fine up until 1.15.0 was released. There have not been any changes or updates to my other plugins.

Things I have tried:
- Deactivating all other plugins and themes
- Updating to latest supported version of WordPress
- Updating to the latest version Booking Activities
- Installing a fresh new version of WordPress with only the Booking Activities and Modern Events Calendar installed

Here is a screen capture of the issue: https://www.screencast.com/t/GSEDkoe6JWm4
In the video, I first demonstrate there is a console error. Afterwards I deactivate Modern Events Calendar to demonstrate that the Booking Activities plugins works by itself. Then I reactivate Modern Events Calendar to once again show the console error appearing.

**Comment by yoancutillas** [comment]
Thank you for your report,
Yes, this is a known compatibility issue (see the [list here](https://booking-activities.fr/en/documentation/faq/))

Modern Event Calendar is using its own version of FullCalendar : /wp-content/plugins/modern-events-calendar/assets/js/mec-general-calendar.js

Booking Activities is using FullCalendar too, so there is a conflict between both versions: /wp-content/plugins/booking-activities/lib/fullcalendar/main.min.js

A good practice would be to check is FullCalendar is already enqueued before enqueuing its own version, like Booking Activities does here:
https://github.com/bookingactivities/booking-activities/blob/1.15.1/booking-activities.php#L172-L180

I cannot know if Modern Event Calendar is doing so, or if it cannot for some reasons, and I have no feedback from the other users who have contacted their support, so you would need to contact their support.

**Comment by dchacon1** [comment]
Thanks for the response. I ended up hosting the latest version of fullcalendar (v5.11.3) on my site and enqueuing the script before any other plugin. Not the greatest solution as far as performance is concerned, but it has remedied the situation for now. 

This solution works because the fullcalendar script checks to see if it has already created the window.FullCalendarVDom object. If it has the script will stop executing.

Like you said, Modern Event Calendar has an older version of the script (v5.9.0). It appears if that version is executed first, later versions will error when checking if window.FullCalendarVDom already exists, however, if the latest version of fullcalendar is executed first there are no errors.

**Comment by yoancutillas** [comment]
Thank you for sharing this additional info and workaround for the users!

The only viable solution is that MEC checks if FullCalendar is already enqueued before enqueuing its own version, hope MEC will add this check.
